// The document the hackathon actually asks for, written from the project rather than about it.
//
// Every entry in this competition owes a STDLIB.md, and the honest version of that document
// is mostly numbers: which packages went, how much of the tree left with them, which Node
// API took over, and what the standard library still does not do. Those are all facts a
// scan already knows, and a person retyping them into markdown will get one of them wrong.
//
// So this generates the tables and refuses to generate the prose. The paragraphs that decide
// whether a write-up is any good -- why these packages, what broke, what you gave up -- are
// left as marked TODOs, because a tool that invented them would be putting words in
// somebody's mouth and they would read like it.
//
// Deterministic on purpose: no timestamp, no username, no node version. The document is
// meant to be committed, and a generator that changes its output when nothing changed makes
// a diff nobody reads.

import { ACTION, RULES } from '../rules/registry.mjs';
import { nodeApiFor } from '../explain/facts.mjs';
import { plural, wrap } from '../text/format.mjs';

/** Markdown prose folds at the width of the terminal it will be read in. */
const COLUMNS = 80;

/** How many rows of "what is left" before the table stops being a table. */
const LEFT = 15;

const para = (text) => wrap(text, COLUMNS, '');

/** A pipe in a cell would end the cell. Nothing we print has one, but a package name is
 * somebody else's string and this is one line. */
const cell = (text) => String(text).split('|').join('\\|');

/** A markdown table, from a header row and body rows. Alignment is not padded: a generated
 * table is read rendered, and padding it makes every diff a whole-table diff. */
function table(headers, rows) {
  return [
    `| ${headers.map(cell).join(' | ')} |`,
    `| ${headers.map(() => '---').join(' | ')} |`,
    ...rows.map((row) => `| ${row.map(cell).join(' | ')} |`),
  ];
}

const moduleOf = (subpath) => subpath.slice(subpath.lastIndexOf('/') + 1);

/** The sites a module's replacement is imported from, once eject or apply has been run. */
function adoptedOf(adoption, name) {
  const found = adoption?.get(name);
  return found === undefined ? null : found;
}

/** One heading per runtime module the project turns out to need. */
function moduleSection(subpath, rules, adoption) {
  const api = nodeApiFor(subpath);
  const lines = [`### ${subpath} — ${rules.map((rule) => rule.package).join(', ')}`, ''];

  if (api.has.length === 0) {
    lines.push(para('Nothing. This is the row with no partial answer in it: Node ships no '
      + 'comparator, no range grammar and no precedence rule, so every line of the '
      + 'replacement had to be written.'), '');
  } else {
    lines.push(...table(['Node API', 'Since', 'What it gives you'], api.has.map((one) => [
      `\`${one.module.slice('node:'.length)}.${one.path}\``, one.version, one.gives,
    ])), '');
  }

  lines.push('What it does not give you, and what the replacement had to add:', '');
  for (const gap of api.lacks) lines.push(`- ${gap}`);

  const adopted = adoptedOf(adoption, moduleOf(subpath));
  if (adopted !== null) {
    // Three ways to have the replacement, and the document should not flatten them: a package
    // subpath, a copy somebody ejected, or this being the tree the module lives in.
    const lead = adopted.home
      ? 'In this project the replacement is a file in this tree rather than a package, imported'
      : adopted.vendored
        ? 'In this project the replacement is a copy in the tree rather than a package, imported'
        : 'In this project the replacement is imported';
    lines.push('', para(`${lead} from ${plural(adopted.files.length, 'file')}, `
      + `${plural(adopted.sites.length, 'site')}.`));
  }
  lines.push('');
  return lines;
}

/**
 * The whole document, as text and as the numbers a caller may want to print instead.
 *
 * @param {object} scan the result of scanProject
 * @param {{ adoption?: Map<string, object>, version?: string|null }} [options]
 */
export function stdlibDocument(scan, options = {}) {
  const adoption = options.adoption ?? null;
  const version = options.version ?? null;
  const name = scan.manifest.name ?? 'this project';
  const replaceable = scan.radius.filter((one) => one.replaceable);
  const rest = scan.radius.filter((one) => !one.replaceable);
  const subpaths = [...new Set(RULES
    .filter((rule) => replaceable.some((one) => one.name === rule.package)
      || adoptedOf(adoption, moduleOf(rule.subpath)) !== null)
    .map((rule) => rule.subpath))];

  const lines = [
    `# STDLIB.md — ${name}`, '',
    para('Where the standard library was enough, and where it stopped.'), '',
    para(`Generated by \`nirdep stdlibmd\`${version === null ? '' : ` ${version}`} from three `
      + 'things this project already has: package.json, the lockfile, and its own imports. '
      + 'The tables below are derived and will be right. The prose between them is yours to '
      + 'write, and every place that needs it is marked TODO.'), '',
  ];

  lines.push('## The claim', '');
  // A module imported straight out of this tree rather than out of a package: nirdep itself,
  // and anything that finished the migration by keeping the files.
  const here = subpaths.filter((subpath) => adoptedOf(adoption, moduleOf(subpath))?.home === true);
  if (scan.counts.direct === 0) {
    // No dependencies means no subtraction, and the else-branch below would print "0 of them
    // are packages nirdep replaces", which is true, useless, and reads like a bug. The
    // interesting number for this project is on the other side of the trade.
    if (here.length > 0) {
      const covered = RULES.filter((rule) => here.includes(rule.subpath));
      const sites = here.reduce((sum, subpath) => sum + adoptedOf(adoption, moduleOf(subpath)).sites.length, 0);
      const touched = new Set(here.flatMap((subpath) => adoptedOf(adoption, moduleOf(subpath)).files));
      lines.push(para(`${name} declares no dependencies. The replacements are not a package it `
        + `installs, they are files in this tree: ${plural(here.length, 'runtime module')} standing `
        + `in for ${plural(covered.length, 'package')}, imported at ${plural(sites, 'site')} across `
        + `${plural(touched.size, 'file')}. There is no subtraction to print below because there `
        + 'is nothing left to subtract from, which is the position the rest of this document is '
        + 'about keeping.'), '');
    } else {
      lines.push(para(`${name} declares no dependencies, so there is nothing here for this `
        + 'document to log: nothing was replaced, because nothing was there. The '
        + `${plural(RULES.length, 'package')} nirdep does replace are listed by \`nirdep explain\`.`), '');
    }
  } else if (replaceable.length === 0 && subpaths.length === 0) {
    lines.push(para(`${name} declares ${plural(scan.counts.direct, 'direct dependency', 'direct dependencies')}`
      + `, and ${scan.counts.direct === 1 ? 'it is not a package nirdep replaces' : 'none of them is a package nirdep replaces'}`
      + '. There is nothing for this document to log yet. The '
      + `${plural(RULES.length, 'package')} it does replace are listed by \`nirdep explain\`.`), '');
  } else {
    const stranded = scan.removable.count;
    // The subtraction reads as a bonus or it reads as padding. `plus 0 that nothing else
    // needs` is padding, so the second clause only appears when there is a second number.
    const seeds = scan.removable.direct.length;
    const also = stranded - seeds;
    lines.push(para(`${name} declares ${plural(scan.counts.direct, 'direct dependency', 'direct dependencies')}`
      + `. ${plural(replaceable.length, 'of them is a package', 'of them are packages')} nirdep `
      + `replaces with a standard-library module`
      + (stranded > 0
        ? `, and removing ${replaceable.length === 1 ? 'it' : 'them'} takes ${stranded} of the `
          + `${scan.removable.of} installed packages out of the tree`
          + (also > 0
            ? `: the ${plural(seeds, 'package')} ${seeds === 1 ? 'itself' : 'themselves'}`
              + `, plus ${plural(also, 'package')} nothing else needs.`
            : `: ${seeds === 1 ? 'itself' : 'themselves'}, and nothing that was there only for `
              + `${seeds === 1 ? 'it' : 'them'}.`)
        : '.')), '');
    if (scan.removable.count > 0 && scan.graph.understood) {
      lines.push(para('That count is an upper bound. The dependency graph is keyed by package '
        + 'name rather than by name and version, so a package installed twice is one node '
        + 'here — which is the direction that over-counts, and it is the direction two of the '
        + 'three lockfile formats leave no way to avoid.'), '');
    }
  }
  // Outside the branches, because the table further down says "no lockfile" in a column
  // whichever branch printed the claim, and a column is not an explanation.
  if (!scan.graph.understood && scan.counts.direct > 0) {
    lines.push(para('No lockfile was read, so there is no tree to subtract from and no '
      + 'transitive count in this document. Commit a lockfile and run it again.'), '');
  }

  if (replaceable.length > 0) {
    lines.push('## What went', '', ...table(
      ['Package', 'Per week', 'Replaced by', 'How', 'Call sites'],
      replaceable.map((one) => {
        const rule = RULES.find((each) => each.package === one.name);
        return [
          `\`${one.name}\``,
          rule?.weekly ?? '—',
          `\`${one.target}\``,
          one.action === ACTION.REWRITE ? 'codemod' : 'by hand',
          one.sites === 0 ? 'declared, not imported' : `${one.sites} in ${plural(one.files, 'file')}`,
        ];
      }),
    ), '');
    lines.push(para('"By hand" is not a hedge about the replacement; it is a statement about '
      + 'the rewrite. Those packages have an API surface a codemod cannot move safely, so '
      + 'nirdep reports the call sites and a person moves them. `nirdep explain <package>` '
      + 'gives the reason, per package.'), '');
  }

  if (subpaths.length > 0) {
    lines.push('## Where the standard library was enough, and where it stopped', '');
    lines.push(para('One heading per replacement, with the Node API it is built on and the '
      + 'part of the job Node does not do. The versions are the ones Node added each API in, '
      + 'which is the number that decides whether this is portable to the runtime you are '
      + 'actually on.'), '');
    for (const subpath of subpaths) {
      lines.push(...moduleSection(subpath, RULES.filter((rule) => rule.subpath === subpath), adoption));
    }
  }

  lines.push('## What is left, and why', '');
  if (scan.counts.direct === 0) {
    lines.push(para('Nothing, and not because the table was filtered: this project declares no '
      + 'dependencies, so there is no row to defend and no sentence owed for one.'), '');
  } else if (rest.length === 0) {
    lines.push(para('Nothing. Every direct dependency this project has is one nirdep '
      + 'replaces, which is a position worth saying out loud.'), '');
  } else {
    const shown = rest.slice(0, LEFT);
    lines.push(...table(['Package', 'Range', 'Would leave with it', 'Imported'], shown.map((one) => [
      `\`${one.name}\``,
      one.range === null ? 'undeclared' : `\`${one.range}\``,
      scan.graph.understood ? plural(one.own.length, 'package') : 'no lockfile',
      one.sites === 0 ? 'no' : `${one.sites} sites`,
    ])), '');
    if (rest.length > shown.length) {
      lines.push(para(`And ${rest.length - shown.length} more, which \`nirdep scan\` lists in full.`), '');
    }
    lines.push(para('TODO: for each of these, one sentence on why it stays. A dependency you '
      + 'chose and can defend is not the same thing as one you inherited, and this table '
      + 'cannot tell the difference.'), '');
  }

  lines.push('## How to check any of this', '');
  lines.push('```sh', 'nirdep scan .          # the numbers above, live',
    'nirdep guard .         # fails a build if one of them comes back',
    'nirdep conformance     # the replacements against their vector corpus', '```', '');

  lines.push('## TODO before you publish this', '');
  for (const prompt of [
    'Why these packages and not others: what made the shortlist worth the work.',
    'What broke. A migration with nothing to report was not a migration.',
    'What you gave up: the feature of the package the replacement does not have.',
    'Where you would not do this again, and what you would depend on instead.',
    'Delete this section.',
  ]) lines.push(`- ${prompt}`);
  lines.push('');

  const markdown = `${lines.join('\n').replace(/\n{3,}/g, '\n\n').trimEnd()}\n`;
  return Object.freeze({
    markdown,
    counts: Object.freeze({
      replaced: replaceable.length,
      modules: subpaths.length,
      remaining: rest.length,
      stranded: scan.removable.count,
      lines: markdown.split('\n').length - 1,
      bytes: Buffer.byteLength(markdown, 'utf8'),
    }),
    // What a caller may want to name without re-deriving it.
    replaced: Object.freeze(replaceable.map((one) => one.name)),
    modules: Object.freeze(subpaths.map(moduleOf)),
    empty: replaceable.length === 0 && subpaths.length === 0,
  });
}
