// The five-second check.
//
// The brief says a judge should be able to confirm zero dependencies in five
// seconds, not five minutes. `npm ls` would only tell you what happens to be
// installed; this proves the stronger claim, that no file in the shipped
// artifact imports anything that is not a Node builtin or a relative path.
//
// Run: node tools/verify.mjs   (or `make verify`)
// Writes deps-proof.txt and exits non-zero if any claim fails.

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { walk, displayPath } from '../src/fs/walk.mjs';
import { auditSource } from '../src/audit/imports.mjs';
import { SOURCE_EXTENSIONS } from '../src/apply/project.mjs';

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const SCANNED = ['bin', 'src', 'tools', 'tests'];
const MANIFEST_FIELDS = ['dependencies', 'devDependencies', 'peerDependencies', 'optionalDependencies'];

const findings = [];
const lines = [];

function claim(ok, text) {
  lines.push(`${ok ? 'PASS' : 'FAIL'}  ${text}`);
  if (!ok) findings.push(text);
}

const manifest = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8'));

lines.push('nirdep -- zero-dependency proof');
lines.push(`generated by: node tools/verify.mjs`);
lines.push(`node: ${process.version}   platform: ${process.platform}`);
lines.push('');
lines.push('1. Manifest');

for (const field of MANIFEST_FIELDS) {
  const value = manifest[field];
  const count = value ? Object.keys(value).length : 0;
  claim(count === 0, `package.json ${field} is empty (${count} entries)`);
}
claim(!existsSync(join(ROOT, 'node_modules')), 'no node_modules directory in the repository');
claim(
  !existsSync(join(ROOT, 'package-lock.json')) || Object.keys(JSON.parse(readFileSync(join(ROOT, 'package-lock.json'), 'utf8')).packages ?? {}).length <= 1,
  'no lockfile entries beyond the root package',
);

lines.push('');
lines.push('2. Every import in the artifact resolves to a Node builtin or a relative path');

const selfNames = new Set(['nirdep', ...Object.keys(manifest.exports ?? {}).map((key) => join('nirdep', key).split('\\').join('/'))]);
const used = new Set();
let imports = 0;
let files = 0;

// One traversal, both answers: the failures in section 2 and the inventory in
// section 3 come from the same scan, so the two sections cannot disagree.
for (const directory of SCANNED) {
  const base = join(ROOT, directory);
  if (!existsSync(base)) continue;
  for (const file of walk(base, { extensions: SOURCE_EXTENSIONS })) {
    files += 1;
    const { specifiers, thirdParty } = auditSource(readFileSync(file, 'utf8'), { selfNames });
    imports += specifiers.length;
    for (const entry of specifiers) {
      if (entry.category === 'builtin') used.add(entry.specifier.replace(/^node:/, ''));
    }
    for (const entry of thirdParty) {
      claim(false, `third-party import ${JSON.stringify(entry.specifier)} at ${displayPath(ROOT, file)}:${entry.line} (${entry.kind})`);
    }
  }
}

claim(findings.length === 0, `${imports} import specifiers checked across ${files} files`);

lines.push('');
lines.push('3. The standard library we actually use');

for (const name of [...used].sort()) lines.push(`      node:${name}`);
lines.push(`      ${used.size} builtin modules, 0 packages`);

lines.push('');
lines.push(findings.length === 0
  ? 'RESULT: zero third-party runtime dependencies.'
  : `RESULT: ${findings.length} problem(s) found.`);

const report = `${lines.join('\n')}\n`;
writeFileSync(join(ROOT, 'deps-proof.txt'), report);
process.stdout.write(report);
process.exit(findings.length === 0 ? 0 : 1);
